apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: docker.io/hoangvv15/reverseproxy:v6
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: env-config

---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  selector:
    app: reverseproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80